#!/bin/bash

# Local utilities, including eg. stuff installed by Homebrew
PATH="$PATH:/usr/local/bin"
# User-specific executables
PATH="$PATH:$HOME/local/bin"
# Miscellaneous (should properly speaking go in $HOME/local)
PATH="$PATH:$HOME/.cask/bin"
PATH="$PATH:/usr/local/opt/go/libexec/bin"
export PATH="$PATH"

export GOPATH="$HOME/projects/go"

# Unlimited history + timestamps
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="%h/%d %H:%M:%S "

# Aliases
alias ec=emacsclient
alias ls="ls -G"
alias peekd="dirs +1"

alias gbs="git bisect start"
alias gbb="git bisect bad"
alias gbg="git bisect good"
alias gbr="git bisect reset"

export EDITOR=emacsclient

# Don't check docstrings (pyflakes)
export PYFLAKES_NODOCTEST=1

# SSH autocomplete
_ssh_comp() {
    perl -ne 'print "$1 " if /^Host (.+)$/' ~/.ssh/config
}
complete -W "$(_ssh_comp)" ssh

# Git setup.
#GIT_PROMPT_ONLY_IN_REPO=1
source ~/src/jvkersch/dotfiles/3rdparty/bash-git-prompt/gitprompt.sh

# Disable git prompt (useful for big repos) by adding "GIT_PROMPT_IGNORE=1" to
# a .bash-git-rc file in the repository root
function disable_git_prompt() {
    local repo=$(git rev-parse --show-toplevel 2> /dev/null)
    if [[ -e "$repo" ]]; then
        echo "GIT_PROMPT_IGNORE=1" >> "$repo/.bash-git-rc"
        echo ".bash-git-rc" >> "$repo/.git/info/exclude"
    fi
}


# Linux-specific stuff
if [[ $(uname) == "Linux" ]]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
    KEY_NAME="id_ecdsa_linux_2017"

    alias rg="ripgrep.rg"
else
    # Assume Darwin
    KEY_NAME="id_rsa_2016"

    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi


# Manage SSH keys via keychain script. This asks for user inpt and so should
# not be run automatically (otherwise it'll interfere with e.g. X session
# manager)
rekeychain() { eval $(keychain --eval --quiet -Q --agents ssh --inherit any "$KEY_NAME") ; ssh-add -l; }

# Convenient aliases
alias ls="ls --color"

alias nb="jupyter notebook"
alias mi="edm shell -e microbiome-dev"
alias mg="edm shell -e metagenome"
alias bd="edm shell -e bacterial-database"
alias mg="edm shell -e metagenome"

alias hatcher="hatcher --url https://packages.enthought.com"
alias utt="~/.edm/envs/edm/bin/utt"

. /home/jvankerschaver/miniconda3/etc/profile.d/conda.sh


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/jvankerschaver/local/google-cloud-sdk/path.bash.inc' ]; then . '/home/jvankerschaver/local/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/jvankerschaver/local/google-cloud-sdk/completion.bash.inc' ]; then . '/home/jvankerschaver/local/google-cloud-sdk/completion.bash.inc'; fi

export WORKON_HOME="$HOME/.edm/envs"
