#!/bin/bash

# Local utilities, including eg. stuff installed by Homebrew
PATH="$PATH:/usr/local/bin"
# User-specific executables
PATH="$PATH:$HOME/local/bin"
# Miscellaneous (should properly speaking go in $HOME/local)
PATH="$PATH:$HOME/miniconda3/bin"
PATH="$PATH:$HOME/.cask/bin"
PATH="$PATH:/usr/local/opt/go/libexec/bin"
export PATH="$PATH"

export GOPATH="$HOME/projects/go"

# Unlimited history + timestamps
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="%h/%d %H:%M:%S "

# Aliases
alias ec=emacsclient
alias ls="ls -G"
alias peekd="dirs +1"

alias gbs="git bisect start"
alias gbb="git bisect bad"
alias gbg="git bisect good"
alias gbr="git bisect reset"

export EDITOR=emacsclient

# Don't check docstrings (pyflakes)
export PYFLAKES_NODOCTEST=1

# SSH autocomplete
_ssh_comp() {
    perl -ne 'print "$1 " if /^Host (.+)$/' ~/.ssh/config
}
complete -W "$(_ssh_comp)" ssh

# Git setup.
#GIT_PROMPT_ONLY_IN_REPO=1
source ~/src/jvkersch/dotfiles/3rdparty/bash-git-prompt/gitprompt.sh


# Linux-specific stuff
if [[ $(uname) == "Linux" ]]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
    KEY_NAME="id_ecdsa_linux_2017"

else
    # Assume Darwin
    KEY_NAME="id_rsa_2016"

    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi


# Manage SSH keys via keychain script. This asks for user inpt and so should
# not be run automatically (otherwise it'll interfere with e.g. X session
# manager)
rekeychain() { eval $(keychain --eval --quiet -Q --agents ssh --inherit any "$KEY_NAME") ; ssh-add -l; }

# Convenient aliases
alias nb="jupyter notebook"
alias mi="edm shell -e microbiome"
alias bd="edm shell -e bacterial-database"

alias hatcher="hatcher --url https://packages.enthought.com"
