#!/bin/bash

# User-specific executables
PATH="$PATH:$HOME/local/bin"
# Emacs Cask
PATH="$PATH:$HOME/.cask/bin"
export PATH="$PATH"

# Unlimited history + timestamps
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="%h/%d %H:%M:%S "

# Use Emacs for local editing; requires Emacs server to be running.
export EDITOR=emacsclient

# Aliases
alias ec=emacsclient
alias ls="ls -G --color"
alias peekd="dirs +1"
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias hatcher="hatcher --url https://packages.enthought.com"
alias utt="~/.edm/envs/edm/bin/utt"

# Command shortcuts
alias nb="jupyter notebook"
alias mi="edm shell -e microbiome-dev"
alias mg="edm shell -e metagenome"
alias bd="edm shell -e bacterial-database"
alias mg="edm shell -e metagenome"

# Useful autocompletions. Requires the bash-completion package.
. /usr/share/bash-completion/bash_completion
. /usr/share/bash-completion/completions/git
. /usr/share/bash-completion/completions/ssh

# Manage SSH keys via keychain script. This asks for user inpt and so should
# not be run automatically (otherwise it'll interfere with e.g. X session
# manager)
function rekeychain() {
    local keyname="id_ecdsa_linux_2017"
    eval $(keychain --eval --quiet -Q --agents ssh --inherit any "$keyname")
    ssh-add -l
}

###############################################################################
# Git setup
###############################################################################

# Git prompt. Relies on script in dotfiles repo.

#GIT_PROMPT_ONLY_IN_REPO=1
source ~/src/jvkersch/dotfiles/3rdparty/bash-git-prompt/gitprompt.sh

# Allow for disabling git prompt (useful for big repos) by adding
# "GIT_PROMPT_IGNORE=1" to a .bash-git-rc file in the repository root
function disable_git_prompt() {
    local repo=$(git rev-parse --show-toplevel 2> /dev/null)
    if [[ -e "$repo" ]]; then
        echo "GIT_PROMPT_IGNORE=1" >> "$repo/.bash-git-rc"
        echo ".bash-git-rc" >> "$repo/.git/info/exclude"
    fi
}

alias gbs="git bisect start"
alias gbb="git bisect bad"
alias gbg="git bisect good"
alias gbr="git bisect reset"


###############################################################################
# Python setup
###############################################################################

# Don't check docstrings (pyflakes)
export PYFLAKES_NODOCTEST=1
export WORKON_HOME="$HOME/.edm/envs"


###############################################################################
# Helper functions
###############################################################################

# Third party environments. We want to keep those out of the PATH
# until we need them.
function activate_conda() {
    local conda_sh="~/miniconda3/etc/profile.d/conda.sh"
    if [ -f "$conda_sh" ]; then
	source "$conda_sh"
    fi
}

function merge() {
    if [ "$#" -ne 2 ]; then
        echo "Usage: merge <folder1> <folder2>"
        echo -n "Merges the content of <folder2> into <folder1>, "
        echo "deleting <folder2> afterwards."
        return
    fi

    local folder1="$1"
    local folder2="$2"
    mv "$folder2"/* "$folder1"
    rmdir "$folder2"
}

# Turn laptop screen off and on; helps with removing artifacts in the
# background due to buggy drivers (sometimes)
function reset_screen() {
    local screen="eDP-1-1"
    xrandr --output "$screen" --off
    xrandr --output "$screen" --auto;
}
