---
- hosts: 127.0.0.1
  connection: local
  pre_tasks:
    - set_fact:
        is_darwin: ansible_os_family|lower == 'darwin'
      tags: ['linux', 'macos']  # XXX
    - block:
        - debug:
            msg: "Running on mac OS"
      when: is_darwin
      tags: ['linux', 'macos']  # XXX
    - block:
        - debug:
            msg: "Running on Linux"
      when: not is_darwin
      tags: ['linux', 'macos']  # XXX
          
  roles:
    - { role: tmux, tags: ['linux', 'macos'] }
    - { role: bash, tags: ['linux', 'macos'] }
    - { role: fish, tags: ['linux', 'macos'] }
    - { role: emacs, tags: ['linux', 'macos'] }
    - { role: python, tags: ['linux', 'macos'] }
    - { role: amethyst, tags: ['macos'] }
    - { role: vscode, tags: ['linux'] }
      #- { role: xorg, tags: ['linux'] }
      #- { role: i3, tags: ['linux'] }
