#+TITLE: My Emacs configuration file
#+AUTHOR: Joris Vankerschaver
#+EMAIL: joris.vankerschaver@gmail.com
#+STARTUP: showall

- Run `cask install` from within .emacs.d folder.
- From within Emacs, run "M-x jedi:install-server"
   (uses system Python by default; needs virtualenv)

* Generic Emacs

** Package management

 #+BEGIN_SRC emacs-lisp
   ;; (require 'cask (expand-file-name "~/.cask/cask.el"))
   ;; (cask-initialize)
   ;; (require 'pallet)
   ;; (pallet-mode t)

   (require 'package)
   (add-to-list 'package-archives
                '("melpa-stable" . "http://stable.melpa.org/packages/"))
   (add-to-list 'package-archives
                '("melpa" . "http://melpa.org/packages/"))
 #+END_SRC

** use-package

   [[https://github.com/jwiegley/use-package][use-package]] is a package to tidy up your .emacs configuration. It allows you
   to run code before or after a package is loaded, set up key bindings for
   modes, in a neat and concise declarative manner.

 #+BEGIN_SRC emacs-lisp
   (eval-when-compile
      (require 'use-package))
 #+END_SRC



** Emacs core


*** Emacs server

Start the Emacs server upon startup.

#+BEGIN_SRC emacs-lisp
(server-start)
#+END_SRC

*** User details

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Joris Vankerschaver"
      user-email-address "Joris.Vankerschaver@gmail.com")
#+END_SRC

*** Emacs customizations

Turn off all the fluff: no splash screen, short y/n answer format instead of
the default yes/no, no tool bar, etc.

#+BEGIN_SRC emacs-lisp
(setq frame-title-format "Emacs: %f")
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq inhibit-splash-screen t)
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Disable C-x C-c to quit emacs, since it is too easy to hit those keys by
mistake. To quit Emacs, use an explicit M-x ~kill-emacs~.

#+BEGIN_SRC emacs-lisp
  (defun disable-exit-keys ()
  (interactive)
    (message "To exit emacs, use M-x kill-emacs"))
  (global-set-key (kbd "C-x C-c") 'disable-exit-keys)
#+END_SRC

Show Emacs with a slightly larger screen. I should probably retire this and
have the window manager take care of this instead.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
  
    ;; (when (display-graphic-p)
    ;;     (if (> (x-display-pixel-width) 1280)
    ;;         (add-to-list 'default-frame-alist (cons 'width 100))
    ;;       (add-to-list 'default-frame-alist (cons 'width 80))))
#+END_SRC

By default Emacs creates backups in the current directory. Create them in a
hidden directory instead, so they're out of the way.

#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
#+END_SRC

