- name: ensure profile directory exists
  file:
    path: ~/.ipython/profile_default/startup
    state: directory

- name: install ipython config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  check_mode: no
  loop:
    - { src: 10-scientific-python.py, dest: ~/.ipython/profile_default/startup/ }
