#! /bin/bash

[[ -f ${HOME}/.bashrc ]] && . ${HOME}/.bashrc

# OPAM configuration
. /Users/jvkersch/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

# added by Miniconda3 4.0.5 installer
#export PATH="/Users/jvkersch/local/miniconda3/bin:$PATH"

export PATH="$HOME/.cargo/bin:$PATH"
